<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rs</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>Rust2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'[a-zA-Z_][a-zA-Z_0-9]*\b(?!')</string>
			<key>name</key>
			<string>storage.modifier.lifetime.rust</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blockComment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|continue|crate|else|extern|for|if|in|let|loop|match|return|unsafe|use|where|while)\b</string>
			<key>name</key>
			<string>keyword.control.rust</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rust</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(fn)\b(?:\s+([a-zA-Z_][a-zA-Z_0-9]*\b))?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.rust</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(struct|enum|mod|trait|type)\b(?:\s+([a-zA-Z_][a-zA-Z_0-9]*\b))?</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Probably not the right way to do it...</string>
			<key>match</key>
			<string>\b(impl|const|static)\b</string>
			<key>name</key>
			<string>storage.type.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|true)\b</string>
			<key>name</key>
			<string>constant.language.bool.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(pub|mut|move|ref)\b</string>
			<key>name</key>
			<string>storage.modifier.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>b?'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rust</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|box)\b</string>
			<key>name</key>
			<string>keyword.operator.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\s*(!\s*)?\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.preprocessor.attribute.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Za-z_][A-Za-z_0-9]+\s*!(?=\s|[\[({])</string>
			<key>name</key>
			<string>support.function.macro.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;&amp;|\|\||==|!=|[&lt;&gt;]=?|-&gt;|::|([-+*/%&amp;|]|&lt;&lt;|&gt;&gt;)=?|[.=!]</string>
			<key>name</key>
			<string>keyword.operator.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|alignof|become|do|final|macro|offsetof|override|priv|proc|pure|sizeof|typeof|unsized|virtual|yield)\b</string>
			<key>name</key>
			<string>invalid.illegal.keyword.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self|Self|[iu](8|16|32|64|size)|f(32|64)|bool|char|str)\b</string>
			<key>name</key>
			<string>storage.type.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>b?"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rust</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9][0-9_]*(\.[0-9_]+)?([Ee][-+]?[0-9_]+)?)([iu](8|16|32|64|size)|f(32|64))?\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0(x[0-9a-fA-F_]+|b[01_]+|o[0-7_]+)([iu](8|16|32|64|size))?\b</string>
			<key>name</key>
			<string>constant.numeric.other.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>b?r(#*)"</string>
			<key>end</key>
			<string>"\1</string>
			<key>name</key>
			<string>string.quoted.double.raw.rust</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.rust</string>
			<key>match</key>
			<string>\b[A-Z][A-Z_]*\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type.rust</string>
			<key>match</key>
			<string>\b[A-Z][A-Za-z_0-9]*\b</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockComment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockComment</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rs2</string>
	<key>uuid</key>
	<string>95B18A68-7DE5-4A70-B57C-77CC1E69BF58</string>
</dict>
</plist>
